# Generated by Django 5.2.1 on 2025-05-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('record_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('tour_request', models.ForeignKey(db_column='tour_request_id', on_delete=django.db.models.deletion.CASCADE, to='tour_requests.tourrequest')),
            ],
            options={
                'db_table': 'service_records',
                'managed': True,
            },
        ),
    ]
