# Generated by Django 5.2.1 on 2025-05-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tour_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('tour_date', models.DateField()),
                ('people_count', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('tour_plan', models.ForeignKey(db_column='tour_plan_id', on_delete=django.db.models.deletion.CASCADE, to='tour_plans.tourplan')),
            ],
            options={
                'db_table': 'tour_requests',
                'managed': True,
            },
        ),
    ]
