# Generated by Django 5.2.1 on 2025-05-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_duration', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tour_plans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TourPlanTouristSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.IntegerField()),
                ('stay_time', models.IntegerField(blank=True, null=True)),
                ('tour_plan', models.ForeignKey(db_column='tour_plan_id', on_delete=django.db.models.deletion.CASCADE, to='tour_plans.tourplan')),
                ('tourist_site', models.ForeignKey(db_column='tourist_site_id', on_delete=django.db.models.deletion.CASCADE, to='tourist_sites.touristsite')),
            ],
            options={
                'db_table': 'tour_plan_tourist_site',
                'managed': True,
                'unique_together': {('tour_plan', 'tourist_site')},
            },
        ),
        migrations.AddField(
            model_name='tourplan',
            name='tourist_sites',
            field=models.ManyToManyField(through='tour_plans.TourPlanTouristSite', to='tourist_sites.touristsite'),
        ),
    ]
