# Generated by Django 5.2.1 on 2025-05-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('site_type', models.CharField(choices=[('natural', 'Natural'), ('cultural', 'Cultural'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tourist_sites',
                'managed': True,
            },
        ),
    ]
